//Yup validation Errors

export const fname_required = "Please Enter Your First Name"
export const min_length = "Too Short"
export const max_length = "Too Long"
export const lname_required = "Please Enter Your Last Name"
export const mobile_required = "Please Enter Your Mobile Number"
export const mobile_regex_match =  "Please enter valid number"
export const email =  "Invalid Email"
export const email_case =  "Email Should be in Lower Case"
export const email_required =  "Please Enter Email"
export const password_required =  "Please Enter Password"
export const password_minlowercase =  "password must contain at least 1 lower case letter"
export const password_minuppercase =  "password must contain at least 1 upper case letter"
export const password_minnumber =  "password must contain at least 1 number"
export const password_minspecialcharacter =  "password must contain at least 1 special character"
export const password_min=   "password must contain 8 or more characters with at least one of each: uppercase, lowercase, number and special"
export const cpassword_required=   "Please Enter Confirm Password"
export const password_match=   "Password didn't match"
export const new_password_match=   "New Password and Confirm Password didn't match"